#!/usr/bin/ruby

require 'clamp'
#https://github.com/fazibear/colorize/blob/master/README.md
#Magenta, Cyan, RGYB, White , Black
require 'colorize'
#http://stackoverflow.com/questions/1050749/including-a-ruby-class-from-a-separate-file
require 'net/ping'
require 'resolv'
require_relative 'lib/host'
require_relative 'lib/db'

class PreParser < Clamp::Command
  option ["-h", "--help"], :flag, "be helpful"
  option ["-v", "--verbose"], :flag, "be verbose"

  parameter "HOST", "Target host"
end

def print_host_list()
  monitordb = SQLite3::Database.new "monitor.db"
  puts "Printing host list"
  monitordb.execute("select * from hosts") do |row|
  #TODO add colors
    p row
  end
end

def print_monitor_list()
  monitordb = SQLite3::Database.new "alerts.db"
  puts "Printing monitor list"
  monitordb.execute("select * from alerts") do |row|
  #TODO add colors
    p row
  end
end

def add_hosts(commands)
  monitordb = SQLite3::Database.new "monitor.db"
  puts "Adding new host"

  if commands.length >= 3
    #Check the first argument after 'add'
    if commands[2] == "help"
      puts "monitor host add <name> [ip]"
      puts "monitor host add hpc-3-3"
      puts "monitor host add hpc-3-3 10.0.3.3"
      puts "monitor host add hpc-3-[1..30].local"
      puts "monitor host add 10.0.3.[1..30]\n\n"
    else
      #Check whether this is a range of hosts or an individual host
      if commands[2].include? "["
        #Split on [X..Y]
        host_prefix = commands[2].split("[")[0]
        host_suffix = commands[2].split("[")[1]
        range = host_suffix.split("]")[0]
        host_suffix = host_suffix.split("]")[1]
        #puts host_prefix
        #puts host_suffix
        #puts range
        low_end = range.split("..")[0]
        high_end = range.split("..")[1]

        #Now that we have all needed numbers lets populate the hosts
        #http://stackoverflow.com/questions/2032875/syntax-for-a-for-loop-in-ruby
        for counter in low_end..high_end
          name = host_prefix + counter + host_suffix
          begin
            ip = Resolv.getaddress name.chomp
            puts ip.chomp+"_(#{name})"
          rescue Errno::EINVAL
            ip = '0.0.0.'+counter
            puts ip.chomp+"_(#{name})"
          end
          #Add hosts to the DB
          monitordb.execute("INSERT INTO hosts (name,ip)
                             VALUES (?, ?)", [name, ip])
        end
      else
        name = commands[2]
        #if defined? commands[3]
        if commands[3] != nil
          ip = commands[3]
          puts ip.chomp+"_(#{name})"
        else
          begin
            ip = Resolv.getaddress name.chomp
            puts ip.chomp+"_(#{name})"
          rescue Errno::EINVAL
            ip = '0.0.0.0'
            puts ip.chomp+"_(#{name})"
          end
        end
        monitordb.execute("INSERT INTO hosts (name,ip)
                           VALUES (?, ?)", [name, ip])
      end
    end
  end
  #Needs input cleaning
end

preparser = PreParser.new File.basename($0), {}
begin
  preparser.parse ARGV
rescue
end

#def execute
# puts "bob" if help?
#end

if preparser.help?
  #puts String.colors
  puts "2017 Comprehensive Simple Monitor".green
  #puts "monitor".colorize(:color => :light_blue, :background => :red) + "host list\n\n"
  #puts "monitor ".colorize(:color => :light_black) + "host list\n\n"
  puts "monitor ".colorize(:color => :magenta) + "host list\n\n"
  exit
end

#if preparser.host?
#  puts "2014 Comprehensive Simple Monitor"
#end

#Open a new Datebase
monitordb = SQLite3::Database.new "monitor.db"

if ARGV[0] == "host"
  #Create host object for the future
  puts "Configuring Host"

  if ARGV[1] == "list"
    print_host_list()
  #Neds input cleaning
  elsif ARGV[1] == "add"
    add_hosts(ARGV)
  elsif ARGV[1] == "discover"
    puts "Discovering new hosts"
    if ARGV[2] == nil
      discovered_ips = `/usr/bin/ruby lib/discover.rb`.split("\n")
      if $?.exitstatus == 1
        puts "Nothing Discovered"
        exit
      end
    else
      discovered_ips = `/usr/bin/ruby lib/discover.rb #{ARGV[2]}`.split("\n")
      if $?.exitstatus == 1
        puts "Nothing Discovered"
        exit
      end
    end

    discovered_ips.each do |ip|
      #[1..-1] removes first char from string
      #chop removes last char from string
      #puts ip.split("_")[0]+"----"+ip.split("_")[1][1..-1].chop
#--This insert needs to be in a function
#--This needs to first check that thes hosts dont already exist, maybe make the IP column inthe DB unique
      monitordb.execute("INSERT INTO hosts (name,ip)
                         VALUES (?, ?)", [ip.split("_")[0], ip.split("_")[1][1..-1].chop])
    end
  elsif ARGV[1] == "remove"
    puts "Removing host"
#add check for IP or Name (regex)
    #db.execute("DELETE from hosts where name = #{ARGV[2]}")
    monitordb.execute("DELETE from hosts where id = #{ARGV[2]}")
  elsif ARGV[1] == "info"
    puts "Printing host monitor info"
    #add check for IP or Name (regex)
    alertsdb = SQLite3::Database.new "alerts.db"
    alertsdb.execute("SELECT * from alerts where name = #{ARGV[2]}")
  else
    puts "Bad host command"
  end
elsif ARGV[0] == "monitor"
  if ARGV[1] == "list"
    print_monitor_list()
  else
    puts "Bad monitor command"
  end
end

def check_connectivity
  monitordb.execute("select * from hosts") do |row|
  end
end


